version: '2'
services:
  mysql:
    image: mariadb:latest
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  memcached:
    image: memcached:latest
    restart: always
  elasticsearch:
    image: elasticsearch:2
    restart: always
  phpfpm:
    depends_on:
      - mysql
      - memcached
      - elasticsearch
    image: cmmarslender/phpfpm:latest
    build: dockerfiles/php-fpm
    volumes:
      - "./wordpress:/var/www/html"
#      - "./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    links:
       - mysql
       - memcached
       - elasticsearch
    restart: always
    extra_hosts:
      - "docker-local.dev:172.18.0.1"
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
    image: nginx:latest
    volumes:
      - "./wordpress:/var/www/html"
      - "./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - phpfpm
    restart: always
