version: '3'
services:
  mysql:
    image: mysql:5
    volumes:
      - "${PWD}/data/db:/var/lib/mysql:delegated"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  mailcatcher:
     image: schickling/mailcatcher
     restart: always
     ports:
       - "1025:1025"
       - "1080:1080"
     environment:
       MAILCATCHER_PORT: 1025
  memcached:
    image: memcached:latest
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ports:
      - "9200:9200"
    volumes:
      - "${PWD}/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "${PWD}/config/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
  phpfpm:
    image: 10up/phpfpm
    depends_on:
      - mysql
      - memcached
      - elasticsearch
    volumes:
      - "${PWD}/wordpress:/var/www/html:cached"
      - "${PWD}/config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "${PWD}/config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - ~/.ssh:/root/.ssh
    restart: always
    extra_hosts:
      - "docker-local.localhost:172.18.0.1"
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - "${PWD}/wordpress:/var/www/html:cached"
      - "${PWD}/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "${PWD}/config/certs:/etc/nginx/certs"
      - "${PWD}/logs/nginx:/var/log/nginx:delegated"
    restart: always
  wpsnapshots:
    image: 10up/wpsnapshots
    depends_on:
      - mysql
      - phpfpm
    volumes:
      - "${PWD}/config/wpsnapshots:/wpsnapshots"
      - "${PWD}/wordpress:/var/www/html"
